final
AndrewRyback/Weather-CSS-HW9 pull request #1
Opened 2024-06-17 16:46 UTC by AndrewRyback

2024-06-21 15:29 UTC, a1exalexander requested changes
Дороби ці моменти і буде апрув! Крім цього всього, зробив непогано!

2024-06-21 15:29 UTC, a1exalexander commented on index.html
багато дуже тегів div, краще всі елементи зробити списком, зрозуміліше стане

2024-06-21 15:29 UTC, a1exalexander commented on style.css
> +    width: 1440px;
дуже погана практика робити фіксовану ширину
![image](https://github.com/AndrewRyback/Weather-CSS-HW9/assets/40409129/b4cafe4b-6756-443f-883b-62d9e3162030)
не зменшується при зменшенні екрану(

2024-06-21 15:29 UTC, a1exalexander commented on style.css
> +    width: 1200px;
те саме стосується кожного елемента, не треба фіксувати ширину

2024-06-21 15:29 UTC, a1exalexander commented on style.css
іконки всі з'їхали
![image](https://github.com/AndrewRyback/Weather-CSS-HW9/assets/40409129/656600f5-cd41-4276-8480-690f26e1e363)

2024-06-21 15:38 UTC, AndrewRyback commented on style.css
з іконками я не зрозумів як іх розтавити правильно

2024-06-21 15:39 UTC, AndrewRyback commented on index.html
я коли намагався зробити списком, всі елементи ставали не рівно, були пробіли і тд. тільки такий спосіб знайшов все розмістити.

2024-06-27 14:40 UTC, a1exalexander requested changes
https://youtu.be/Bvg-uGSf4X0?t=2167

потрібно вирівняти текст і іконки відповідно до макета

2024-06-27 14:40 UTC, a1exalexander commented on style.css
https://youtu.be/Bvg-uGSf4X0?t=2167

2024-06-27 14:40 UTC, a1exalexander commented on style.css
подивись ще раз відео з уроку, я робив це завдання частково, іконки вирівнював

2024-07-05 11:00 UTC, a1exalexander approved these changes
![image](https://github.com/AndrewRyback/Weather-CSS-HW9/assets/40409129/125d6986-643d-48f9-9509-c7b9a13d4648)
Приймається але контейнер виправ

2024-07-09 15:55 UTC, a1exalexander approved these changes

2024-07-10 04:31 UTC, merged